### ISSUE TITLE
Self-closing tags arent parsed properly

### ISSUE THREAD

**Issue by ccorcos** [posthtml/posthtml-parser#23]
```
const parse = require('posthtml-parser')
const result = parse("<p> Hello <World/> yes</p>")
console.log(JSON.stringify(result, undefined, 2))
[
  {
    "tag": "p",
    "content": [
      " Hello ",
      {
        "tag": "World",
        "content": [
          " yes"
        ]
      }
    ]
  }
]
```

**Comment by GitScrum** [comment]
@ccorcos Hi, if use in options xmlMode: true and use notation <cutom-tag /> will be good

**Comment by ccorcos** [comment]
Thanks!

**Comment by dy** [comment]
Just stumbled upon that in https://github.com/parcel-bundler/parcel/issues/3486 and https://github.com/posthtml/posthtml-include/issues/28 - such a blocker.

**Comment by Scrum** [comment]
@dy Hi, I see that both tasks are closed - should I take some action?

**Comment by dy** [comment]
The correct behavior for the parser would be throwing an error in the case where unclosed tags are met, instead of silently returning wrongly parsed HTML.
I'd add that test case:
```html
<include src="a.html"/>
<include src="b.html"/>
```
Otherwise I've spent, like, ~2 hours figuring that out, somebody else can get trapped there too.

**Comment by Scrum** [comment]
@dy Good day to you wherever you are.

I am sorry that you had to spend 2 hours of your life to find a reason instead of comfortable and productive programming, accept my condolences for your loss.

I updated the [documentation](https://github.com/posthtml/posthtml-parser#xmlmode), I think it will help not to spend ~ 2 hours looking for a problem. 

> The correct behavior for the parser would be throwing an error in the case where unclosed tags are met, instead of silently returning wrongly parsed HTML. Otherwise that's really confusing from the level of dependent packages like posthtml-include.

> I'd add that test case:

I put your proposal into a separate [task](https://github.com/posthtml/posthtml-parser/issues/34) and I will try to consider and take all measures on it to eliminate this problem. Perhaps you can do it faster and if this happens do not hesitate to send PR 👍

**Comment by silvenon** [comment]
Thank you! I'm from the future to confirm that you indeed saved me a lot of time!
